services:
  nginx:
    image: nginx:alpine
    container_name: wp-nginx-${PROJECT_NAME}
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
    networks:
      - backend
    depends_on:
      - php

  php:
    build: docker/php
    user: "${UID:-1000}:${GID:-1000}"
    container_name: wp-php-${PROJECT_NAME}
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - backend
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.11
    container_name: wp-db-${PROJECT_NAME}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: wp-redis-${PROJECT_NAME}
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  db:
