services:
  nginx:
    container_name: wp-nginx-${PROJECT_NAME}
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp-${PROJECT_NAME}.rule=Host(`${PROJECT_DOMAIN}`)"
      - "traefik.http.routers.wp-${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.wp-${PROJECT_NAME}.tls=true"
      - "traefik.http.routers.wp-${PROJECT_NAME}.service=wp-${PROJECT_NAME}"
      - "traefik.http.services.wp-${PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=backend"
    networks:
      - backend
      - internal

  php:
    container_name: wp-php-${PROJECT_NAME}
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      backend:
      internal:
        aliases:
          - php-fpm

  redis:
    container_name: wp-redis-${PROJECT_NAME}
    image: redis:5-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - internal

networks:
  backend:
    external: true
  internal:
    driver: bridge
